# Generated by Django 5.1.3 on 2025-07-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
