# Generated by Django 5.1.3 on 2025-06-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotusersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='Tg id')),
            ],
            options={
                'verbose_name': 'BotusersModel',
                'verbose_name_plural': 'BotusersModels',
                'db_table': 'botusers',
            },
        ),
    ]
