# Generated by Django 5.1.3 on 2025-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_botusersmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusersmodel',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Ism'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botusersmodel',
            name='tg_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Tg id'),
            preserve_default=False,
        ),
    ]
