# Generated by Django 5.1.3 on 2025-06-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_botusersmodel_name_alter_botusersmodel_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusersmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='botusersmodel',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botusersmodel',
            name='last_name',
            field=models.CharField(default=1, max_length=200, verbose_name='last_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botusersmodel',
            name='photo_url',
            field=models.URLField(default=1, verbose_name='Photo url'),
            preserve_default=False,
        ),
    ]
