# Generated by Django 5.1.3 on 2025-06-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_botusersmodel_name_botusersmodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusersmodel',
            name='photo_url',
            field=models.TextField(verbose_name='Photo url'),
        ),
    ]
