# Generated by Django 5.1.3 on 2025-06-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'AmenityModel',
                'verbose_name_plural': 'AmenityModels',
                'db_table': 'Amenity',
            },
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='area',
            field=models.CharField(default=1, max_length=200, verbose_name='kv.metr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='building',
            field=models.CharField(choices=[('brick', 'G‘isht'), ('monolith', 'Monolit'), ('block', 'Beton bloklari'), ('concrete', 'Beton'), ('other', 'Boshqa')], default='brick', max_length=100, verbose_name='Qurilish Materiallari'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='currency',
            field=models.CharField(choices=[('uzs', "So'm"), ('shb', 'Sh.b')], default='uzs', max_length=10, verbose_name='Valyuta Turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ochiqlama'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nechinchi qavatda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='price_type',
            field=models.CharField(choices=[('total', 'Umumiy Narx'), ('square', 'Narx m2')], default='total', max_length=100, verbose_name='Narx Turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.propertymodel', verbose_name='Mulk turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='repair_type',
            field=models.CharField(choices=[('author', 'Avtorlik loyihasi'), ('euro', 'Evrotamir'), ('medium', 'O‘rta'), ('needs_repair', 'Ta’mir talab'), ('black_finish', 'Qora suvoq')], default='author', max_length=200, verbose_name='Remont turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='room_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Xonalar soni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='total_floors',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Binoni jami qavatlari'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
