# Generated by Django 5.1.3 on 2025-06-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorymodel_name_en_categorymodel_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='districtmodel',
            name='name_en',
        ),
    ]
