# Generated by Django 5.1.3 on 2025-06-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_amenitymodel_listingmodel_area_listingmodel_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='amenity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.amenitymodel', verbose_name='Quylaylik'),
        ),
    ]
