# Generated by Django 5.1.3 on 2025-06-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_categorymodel_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='dealtype',
            field=models.CharField(blank=True, choices=[('sale', 'Sotiladi'), ('rent', 'Ijaraga beriladi')], default='rent', max_length=100, null=True, verbose_name='Bitim turi'),
        ),
    ]
