# Generated by Django 5.1.3 on 2025-06-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_listingmodel_amenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingimageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listing/', verbose_name='Rasmlar')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.listingmodel', verbose_name='Uy elonlari')),
            ],
            options={
                'verbose_name': 'ListingimageModel',
                'verbose_name_plural': 'ListingimageModels',
                'db_table': 'ListingImage',
            },
        ),
    ]
