# Generated by Django 5.1.3 on 2025-06-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_listingimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
