# Generated by Django 5.1.3 on 2025-06-21 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_propertymodel_dealtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ListingModel',
                'verbose_name_plural': 'ListingModels',
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='ListingsubtypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listingmodel', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'ListingsubtypeModel',
                'verbose_name_plural': 'ListingsubtypeModels',
                'db_table': 'listingSubType',
            },
        ),
    ]
