# Generated by Django 5.1.3 on 2025-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_listingmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='amenity',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='amenity',
            field=models.ManyToManyField(blank=True, null=True, to='api.amenitymodel', verbose_name='Quylaylik'),
        ),
    ]
