# Generated by Django 5.1.3 on 2025-06-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_listingmodel_amenity_listingmodel_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='price_shb',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Narx (Sh.B.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='price_uzs',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Narx (UZS)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingimagemodel',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.listingmodel', verbose_name='Uy elonlari'),
        ),
    ]
