# Generated by Django 5.1.3 on 2025-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_listingmodel_price_listingmodel_price_shb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingmaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'BuildingmaterialModel',
                'verbose_name_plural': 'BuildingmaterialModels',
                'db_table': 'buildingMaterial',
            },
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='apartment_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Kvartira maydoni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='apartment_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kvartira turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='building_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Bino maydoni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Biznes turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='construction_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Qurilish maydoni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='floors_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Qavatlar soni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='house_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Uy maydoni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='house_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Yer maydoni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='land_type',
            field=models.CharField(blank=True, choices=[('residential', 'Turar joy'), ('non-residential', 'Noturar joy')], default='residential', max_length=100, null=True, verbose_name='Yer turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='negotiable',
            field=models.BooleanField(default=False, verbose_name='Kelishiladi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='office_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Ofis maydoni'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='property_subtype',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='residential_complex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Turar joy majmuasi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='room_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Xona maydoni'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='property',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mulk Turi'),
        ),
    ]
