# Generated by Django 5.1.3 on 2025-06-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_amenitymodel_name_ru_amenitymodel_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='property_subtype',
        ),
    ]
