# Generated by Django 5.1.3 on 2025-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_listingmodel_property_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='apartment_type',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='land_type',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='residential_complex',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='property_subtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mulk quyi turi'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nechinchi qavatda'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='repair_type',
            field=models.CharField(blank=True, choices=[('author', 'Avtorlik loyihasi'), ('euro', 'Evrotamir'), ('medium', 'O‘rta'), ('needs_repair', 'Ta’mir talab'), ('black_finish', 'Qora suvoq')], default='author', max_length=200, null=True, verbose_name='Remont turi'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Binoni jami qavatlari'),
        ),
    ]
