# Generated by Django 5.1.3 on 2025-06-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_listingmodel_apartment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='price_shb',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='price_uzs',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Narx'),
        ),
    ]
