# Generated by Django 5.1.3 on 2025-06-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_listingmodel_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialcomplexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ResidentialcomplexModel',
                'verbose_name_plural': 'ResidentialcomplexModels',
                'db_table': 'ResidentialComplex',
            },
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='residential_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.residentialcomplexmodel', verbose_name='Complex'),
        ),
    ]
