# Generated by Django 5.1.3 on 2025-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_residentialcomplexmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplexmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='residentialcomplexmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
