# Generated by Django 5.1.3 on 2025-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_residentialcomplexmodel_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='area',
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price_type',
            field=models.CharField(choices=[('total', 'Umumiy Narx'), ('square', 'Narx m2'), ('salePrice', 'Narxi (Sotuv)'), ('monthly', 'Oylik'), ('daily', 'Kunlik')], default='total', max_length=100, verbose_name='Narx Turi'),
        ),
    ]
