# Generated by Django 5.1.3 on 2025-06-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_listingmodel_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='currency',
            field=models.CharField(choices=[('uzs', "So'm"), ('shb', 'Sh.b')], default='uzs', max_length=100, verbose_name='Valyuta'),
        ),
    ]
