# Generated by Django 5.1.3 on 2025-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_listingmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nechinchi qavatda'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='floors_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qavatlar soni'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='room_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xonalar soni'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='total_floors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Binoni jami qavatlari'),
        ),
    ]
