# Generated by Django 5.1.3 on 2025-06-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_listingmodel_floor_and_more'),
        ('users', '0003_alter_botusersmodel_name_alter_botusersmodel_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.botusersmodel'),
        ),
    ]
