# Generated by Django 5.1.3 on 2025-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_favoritemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Top elonmi'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='top_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='top_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
