# Generated by Django 5.1.3 on 2025-07-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_listingmodel_is_top_listingmodel_top_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activmi ?'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Top elonmi ?'),
        ),
    ]
