# Generated by Django 5.1.3 on 2025-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_listingmodel_is_active_alter_listingmodel_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=50, verbose_name='Karta raqam')),
                ('top_price', models.CharField(blank=True, help_text='(1 kunlik narx)', max_length=100, null=True, verbose_name='Top elon kunlik narxi')),
                ('listing_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Elon narxi')),
            ],
            options={
                'verbose_name': 'PaymentModel',
                'verbose_name_plural': 'PaymentModels',
                'db_table': 'payment',
            },
        ),
    ]
