# Generated by Django 5.1.3 on 2025-07-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='check/', verbose_name='Check')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.listingmodel', verbose_name='Elon')),
            ],
            options={
                'verbose_name': 'CheckModel',
                'verbose_name_plural': 'CheckModels',
                'db_table': 'check',
            },
        ),
    ]
