# Generated by Django 5.1.3 on 2025-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_checkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='card_owner',
            field=models.CharField(default=1, max_length=200, verbose_name='Karta egasi'),
            preserve_default=False,
        ),
    ]
