# Generated by Django 5.1.3 on 2025-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_paymentmodel_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=100, verbose_name='Status'),
        ),
    ]
