# Generated by Django 5.1.3 on 2025-07-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_toplistingpricemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='toplisting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.toplistingpricemodel', verbose_name='Top Elon kunlari'),
        ),
    ]
