# Generated by Django 5.1.3 on 2025-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_listingmodel_toplisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='top_end_date',
        ),
        migrations.AlterField(
            model_name='toplistingpricemodel',
            name='day',
            field=models.CharField(max_length=255, verbose_name='Kun'),
        ),
    ]
