# Generated by Django 5.1.3 on 2025-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_listingmodel_top_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Viloyat'),
        ),
    ]
