# Generated by Django 5.1.3 on 2025-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_listingmodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan')], default='pending', max_length=100, verbose_name='Status'),
        ),
    ]
