# Generated by Django 5.1.3 on 2025-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_listingmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
