# Generated by Django 5.1.3 on 2025-08-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_listingmodel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemodel',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to='api.listingmodel', verbose_name='elon'),
        ),
    ]
