# Generated by Django 5.1.3 on 2025-10-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_favoritemodel_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='toplisting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.toplistingpricemodel', verbose_name='Top Elon kunlari'),
        ),
    ]
